# General settings
seed: 42
device: "cuda"  # "cpu" or "cuda"

# Dataset settings
dataset:
  name: "COCO"
  path: "/path/to/coco/dataset"
  train_split: "train"
  val_split: "val"
  test_split: "test"

# Detector network settings
detector_network:
  backbone: "resnet50"
  pretrained_backbone: True
  num_classes: 81

# Region proposal network settings
region_proposal_network:
  anchor_ratios: [0.5, 1, 2]
  anchor_sizes: [128, 256, 512]
  anchor_strides: [16]

# Bounding box regressor settings
bounding_box_regressor:
  regression_loss: "smooth_l1"

# Object classifier settings
object_classifier:
  classification_loss: "cross_entropy"

# Reinforcement learning agent settings
reinforcement_learning_agent:
  algorithm: "DQN"
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 0.995
  gamma: 0.99
  learning_rate: 0.0001
  memory_size: 100000
  batch_size: 32
  update_interval: 1000

# Training settings
training:
  num_epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0005
  batch_size: 16
  num_workers: 4
  checkpoint_interval: 10

# Evaluation settings
evaluation:
  iou_threshold: 0.5
  score_threshold: 0.5
  nms_threshold: 0.5
